[[roles]]
name = "qbittorrent"
# Define a list of routes with the syntax "Http-Method /path"
routes = ["GET /v1/portforward", "GET /v1/vpn/status"]
# No auth required since the control server port will not be exposed publically
auth = "none"
# auth = "basic"
# username = "myusername"
# password = "mypassword"

